name: zenzen
description: leave from many channels on Slack.You can also rejoin the channel from which you left.
version: 1.0.0
homepage: https://github.com/operando/zenzen

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  path: ^1.7.0
  json_annotation: ^3.0.0
  http: ^0.12.2
  intl: ^0.16.1
  toml: ^0.6.0
  args: ^1.6.0
  logging: ^0.11.4

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
  build_runner: ^1.0.0
  json_serializable: ^3.2.0
